# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/revathy/Revathy/github/9Nov/rtMessage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/revathy/Revathy/github/9Nov/rtMessage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/revathy/Revathy/github/9Nov/rtMessage/CMakeFiles /home/revathy/Revathy/github/9Nov/rtMessage/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/revathy/Revathy/github/9Nov/rtMessage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rtrouted_app

# Build rule for target.
rtrouted_app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtrouted_app
.PHONY : rtrouted_app

# fast build rule for target.
rtrouted_app/fast:
	$(MAKE) -f CMakeFiles/rtrouted_app.dir/build.make CMakeFiles/rtrouted_app.dir/build
.PHONY : rtrouted_app/fast

#=============================================================================
# Target rules for targets named rtMessaging_lib

# Build rule for target.
rtMessaging_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtMessaging_lib
.PHONY : rtMessaging_lib

# fast build rule for target.
rtMessaging_lib/fast:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/build
.PHONY : rtMessaging_lib/fast

#=============================================================================
# Target rules for targets named rtmessage_sample_app_send

# Build rule for target.
rtmessage_sample_app_send: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtmessage_sample_app_send
.PHONY : rtmessage_sample_app_send

# fast build rule for target.
rtmessage_sample_app_send/fast:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_send.dir/build.make CMakeFiles/rtmessage_sample_app_send.dir/build
.PHONY : rtmessage_sample_app_send/fast

#=============================================================================
# Target rules for targets named rtmessage_sample_app_res

# Build rule for target.
rtmessage_sample_app_res: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtmessage_sample_app_res
.PHONY : rtmessage_sample_app_res

# fast build rule for target.
rtmessage_sample_app_res/fast:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_res.dir/build.make CMakeFiles/rtmessage_sample_app_res.dir/build
.PHONY : rtmessage_sample_app_res/fast

#=============================================================================
# Target rules for targets named rtmessage_sample_app_recv

# Build rule for target.
rtmessage_sample_app_recv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtmessage_sample_app_recv
.PHONY : rtmessage_sample_app_recv

# fast build rule for target.
rtmessage_sample_app_recv/fast:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_recv.dir/build.make CMakeFiles/rtmessage_sample_app_recv.dir/build
.PHONY : rtmessage_sample_app_recv/fast

#=============================================================================
# Target rules for targets named rtmessage_sample_app_req

# Build rule for target.
rtmessage_sample_app_req: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtmessage_sample_app_req
.PHONY : rtmessage_sample_app_req

# fast build rule for target.
rtmessage_sample_app_req/fast:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_req.dir/build.make CMakeFiles/rtmessage_sample_app_req.dir/build
.PHONY : rtmessage_sample_app_req/fast

rtConnection.o: rtConnection.c.o

.PHONY : rtConnection.o

# target to build an object file
rtConnection.c.o:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtConnection.c.o
.PHONY : rtConnection.c.o

rtConnection.i: rtConnection.c.i

.PHONY : rtConnection.i

# target to preprocess a source file
rtConnection.c.i:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtConnection.c.i
.PHONY : rtConnection.c.i

rtConnection.s: rtConnection.c.s

.PHONY : rtConnection.s

# target to generate assembly for a file
rtConnection.c.s:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtConnection.c.s
.PHONY : rtConnection.c.s

rtEncoder.o: rtEncoder.c.o

.PHONY : rtEncoder.o

# target to build an object file
rtEncoder.c.o:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtEncoder.c.o
.PHONY : rtEncoder.c.o

rtEncoder.i: rtEncoder.c.i

.PHONY : rtEncoder.i

# target to preprocess a source file
rtEncoder.c.i:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtEncoder.c.i
.PHONY : rtEncoder.c.i

rtEncoder.s: rtEncoder.c.s

.PHONY : rtEncoder.s

# target to generate assembly for a file
rtEncoder.c.s:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtEncoder.c.s
.PHONY : rtEncoder.c.s

rtError.o: rtError.c.o

.PHONY : rtError.o

# target to build an object file
rtError.c.o:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtError.c.o
.PHONY : rtError.c.o

rtError.i: rtError.c.i

.PHONY : rtError.i

# target to preprocess a source file
rtError.c.i:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtError.c.i
.PHONY : rtError.c.i

rtError.s: rtError.c.s

.PHONY : rtError.s

# target to generate assembly for a file
rtError.c.s:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtError.c.s
.PHONY : rtError.c.s

rtLog.o: rtLog.c.o

.PHONY : rtLog.o

# target to build an object file
rtLog.c.o:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtLog.c.o
.PHONY : rtLog.c.o

rtLog.i: rtLog.c.i

.PHONY : rtLog.i

# target to preprocess a source file
rtLog.c.i:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtLog.c.i
.PHONY : rtLog.c.i

rtLog.s: rtLog.c.s

.PHONY : rtLog.s

# target to generate assembly for a file
rtLog.c.s:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtLog.c.s
.PHONY : rtLog.c.s

rtMessage.o: rtMessage.c.o

.PHONY : rtMessage.o

# target to build an object file
rtMessage.c.o:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtMessage.c.o
.PHONY : rtMessage.c.o

rtMessage.i: rtMessage.c.i

.PHONY : rtMessage.i

# target to preprocess a source file
rtMessage.c.i:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtMessage.c.i
.PHONY : rtMessage.c.i

rtMessage.s: rtMessage.c.s

.PHONY : rtMessage.s

# target to generate assembly for a file
rtMessage.c.s:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtMessage.c.s
.PHONY : rtMessage.c.s

rtMessageHeader.o: rtMessageHeader.c.o

.PHONY : rtMessageHeader.o

# target to build an object file
rtMessageHeader.c.o:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtMessageHeader.c.o
.PHONY : rtMessageHeader.c.o

rtMessageHeader.i: rtMessageHeader.c.i

.PHONY : rtMessageHeader.i

# target to preprocess a source file
rtMessageHeader.c.i:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtMessageHeader.c.i
.PHONY : rtMessageHeader.c.i

rtMessageHeader.s: rtMessageHeader.c.s

.PHONY : rtMessageHeader.s

# target to generate assembly for a file
rtMessageHeader.c.s:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtMessageHeader.c.s
.PHONY : rtMessageHeader.c.s

rtSocket.o: rtSocket.c.o

.PHONY : rtSocket.o

# target to build an object file
rtSocket.c.o:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtSocket.c.o
.PHONY : rtSocket.c.o

rtSocket.i: rtSocket.c.i

.PHONY : rtSocket.i

# target to preprocess a source file
rtSocket.c.i:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtSocket.c.i
.PHONY : rtSocket.c.i

rtSocket.s: rtSocket.c.s

.PHONY : rtSocket.s

# target to generate assembly for a file
rtSocket.c.s:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtSocket.c.s
.PHONY : rtSocket.c.s

rtVector.o: rtVector.c.o

.PHONY : rtVector.o

# target to build an object file
rtVector.c.o:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtVector.c.o
.PHONY : rtVector.c.o

rtVector.i: rtVector.c.i

.PHONY : rtVector.i

# target to preprocess a source file
rtVector.c.i:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtVector.c.i
.PHONY : rtVector.c.i

rtVector.s: rtVector.c.s

.PHONY : rtVector.s

# target to generate assembly for a file
rtVector.c.s:
	$(MAKE) -f CMakeFiles/rtMessaging_lib.dir/build.make CMakeFiles/rtMessaging_lib.dir/rtVector.c.s
.PHONY : rtVector.c.s

rtrouted.o: rtrouted.c.o

.PHONY : rtrouted.o

# target to build an object file
rtrouted.c.o:
	$(MAKE) -f CMakeFiles/rtrouted_app.dir/build.make CMakeFiles/rtrouted_app.dir/rtrouted.c.o
.PHONY : rtrouted.c.o

rtrouted.i: rtrouted.c.i

.PHONY : rtrouted.i

# target to preprocess a source file
rtrouted.c.i:
	$(MAKE) -f CMakeFiles/rtrouted_app.dir/build.make CMakeFiles/rtrouted_app.dir/rtrouted.c.i
.PHONY : rtrouted.c.i

rtrouted.s: rtrouted.c.s

.PHONY : rtrouted.s

# target to generate assembly for a file
rtrouted.c.s:
	$(MAKE) -f CMakeFiles/rtrouted_app.dir/build.make CMakeFiles/rtrouted_app.dir/rtrouted.c.s
.PHONY : rtrouted.c.s

sample_recv.o: sample_recv.c.o

.PHONY : sample_recv.o

# target to build an object file
sample_recv.c.o:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_recv.dir/build.make CMakeFiles/rtmessage_sample_app_recv.dir/sample_recv.c.o
.PHONY : sample_recv.c.o

sample_recv.i: sample_recv.c.i

.PHONY : sample_recv.i

# target to preprocess a source file
sample_recv.c.i:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_recv.dir/build.make CMakeFiles/rtmessage_sample_app_recv.dir/sample_recv.c.i
.PHONY : sample_recv.c.i

sample_recv.s: sample_recv.c.s

.PHONY : sample_recv.s

# target to generate assembly for a file
sample_recv.c.s:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_recv.dir/build.make CMakeFiles/rtmessage_sample_app_recv.dir/sample_recv.c.s
.PHONY : sample_recv.c.s

sample_req.o: sample_req.c.o

.PHONY : sample_req.o

# target to build an object file
sample_req.c.o:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_req.dir/build.make CMakeFiles/rtmessage_sample_app_req.dir/sample_req.c.o
.PHONY : sample_req.c.o

sample_req.i: sample_req.c.i

.PHONY : sample_req.i

# target to preprocess a source file
sample_req.c.i:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_req.dir/build.make CMakeFiles/rtmessage_sample_app_req.dir/sample_req.c.i
.PHONY : sample_req.c.i

sample_req.s: sample_req.c.s

.PHONY : sample_req.s

# target to generate assembly for a file
sample_req.c.s:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_req.dir/build.make CMakeFiles/rtmessage_sample_app_req.dir/sample_req.c.s
.PHONY : sample_req.c.s

sample_res.o: sample_res.c.o

.PHONY : sample_res.o

# target to build an object file
sample_res.c.o:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_res.dir/build.make CMakeFiles/rtmessage_sample_app_res.dir/sample_res.c.o
.PHONY : sample_res.c.o

sample_res.i: sample_res.c.i

.PHONY : sample_res.i

# target to preprocess a source file
sample_res.c.i:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_res.dir/build.make CMakeFiles/rtmessage_sample_app_res.dir/sample_res.c.i
.PHONY : sample_res.c.i

sample_res.s: sample_res.c.s

.PHONY : sample_res.s

# target to generate assembly for a file
sample_res.c.s:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_res.dir/build.make CMakeFiles/rtmessage_sample_app_res.dir/sample_res.c.s
.PHONY : sample_res.c.s

sample_send.o: sample_send.c.o

.PHONY : sample_send.o

# target to build an object file
sample_send.c.o:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_send.dir/build.make CMakeFiles/rtmessage_sample_app_send.dir/sample_send.c.o
.PHONY : sample_send.c.o

sample_send.i: sample_send.c.i

.PHONY : sample_send.i

# target to preprocess a source file
sample_send.c.i:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_send.dir/build.make CMakeFiles/rtmessage_sample_app_send.dir/sample_send.c.i
.PHONY : sample_send.c.i

sample_send.s: sample_send.c.s

.PHONY : sample_send.s

# target to generate assembly for a file
sample_send.c.s:
	$(MAKE) -f CMakeFiles/rtmessage_sample_app_send.dir/build.make CMakeFiles/rtmessage_sample_app_send.dir/sample_send.c.s
.PHONY : sample_send.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rtrouted_app"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... rtMessaging_lib"
	@echo "... rtmessage_sample_app_send"
	@echo "... rtmessage_sample_app_res"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... rtmessage_sample_app_recv"
	@echo "... rtmessage_sample_app_req"
	@echo "... install/local"
	@echo "... rtConnection.o"
	@echo "... rtConnection.i"
	@echo "... rtConnection.s"
	@echo "... rtEncoder.o"
	@echo "... rtEncoder.i"
	@echo "... rtEncoder.s"
	@echo "... rtError.o"
	@echo "... rtError.i"
	@echo "... rtError.s"
	@echo "... rtLog.o"
	@echo "... rtLog.i"
	@echo "... rtLog.s"
	@echo "... rtMessage.o"
	@echo "... rtMessage.i"
	@echo "... rtMessage.s"
	@echo "... rtMessageHeader.o"
	@echo "... rtMessageHeader.i"
	@echo "... rtMessageHeader.s"
	@echo "... rtSocket.o"
	@echo "... rtSocket.i"
	@echo "... rtSocket.s"
	@echo "... rtVector.o"
	@echo "... rtVector.i"
	@echo "... rtVector.s"
	@echo "... rtrouted.o"
	@echo "... rtrouted.i"
	@echo "... rtrouted.s"
	@echo "... sample_recv.o"
	@echo "... sample_recv.i"
	@echo "... sample_recv.s"
	@echo "... sample_req.o"
	@echo "... sample_req.i"
	@echo "... sample_req.s"
	@echo "... sample_res.o"
	@echo "... sample_res.i"
	@echo "... sample_res.s"
	@echo "... sample_send.o"
	@echo "... sample_send.i"
	@echo "... sample_send.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

